import type { PublicPhotoSelection } from './repository'

export function devPhotoSelectionFixture(): PublicPhotoSelection | null {
  return {
    id: 'dev-fixture',
    publishedAt: new Date(),
    items: [
      {
        id: 'dev-photo-0',
        url: '/images/photos/photo-1.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1200,
        height: 1600,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 0 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-1',
        url: '/images/photos/photo-2.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1200,
        height: 1600,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-2',
        url: '/images/photos/photo-3.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 2208,
        height: 2992,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-3',
        url: '/images/photos/photo-4.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1200,
        height: 1600,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-4',
        url: '/images/photos/photo-5.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-5',
        url: '/images/photos/photo-6.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1200,
        height: 1600,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-6',
        url: '/images/photos/photo-7.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1280,
        height: 960,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-7',
        url: '/images/photos/photo-8.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-8',
        url: '/images/photos/photo-9.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-9',
        url: '/images/photos/photo-10.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1206,
        height: 883,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-10',
        url: '/images/photos/photo-11.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 982,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-11',
        url: '/images/photos/photo-12.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 11 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-12',
        url: '/images/photos/photo-13.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-13',
        url: '/images/photos/photo-14.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 720,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 13 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-14',
        url: '/images/photos/photo-15.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 720,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-15',
        url: '/images/photos/photo-16.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 720,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-16',
        url: '/images/photos/photo-17.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 720,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 16 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-17',
        url: '/images/photos/photo-18.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 720,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 17 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-18',
        url: '/images/photos/photo-19.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 18 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-19',
        url: '/images/photos/photo-20.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1280,
        height: 960,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 19 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-20',
        url: '/images/photos/photo-21.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 1280,
        height: 960,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-21',
        url: '/images/photos/photo-22.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 21 * 86400000).toISOString(),
      },
      {
        id: 'dev-photo-22',
        url: '/images/photos/photo-23.jpg',
        blurDataURL: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
        width: 960,
        height: 1280,
        model: 'iPhone 15 Pro',
        make: 'Apple',
        lens: 'Main Camera',
        focalLength: '24mm',
        fNumber: 'f/1.78',
        iso: '100',
        exposureTime: '1/200',
        capturedAt: new Date(Date.now() - 22 * 86400000).toISOString(),
      },
    ],
  }
}
