export const STATIC_PHOTOS = [
  {
    id: 'photo-1.jpeg',
    src: '/photos/photo-1.jpeg',
    width: 2048,
    height: 1536,
    alt: 'Photo photo-1.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-10.jpeg',
    src: '/photos/photo-10.jpeg',
    width: 960,
    height: 1280,
    alt: 'Photo photo-10.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-11.jpeg',
    src: '/photos/photo-11.jpeg',
    width: 1280,
    height: 960,
    alt: 'Photo photo-11.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-12.jpeg',
    src: '/photos/photo-12.jpeg',
    width: 1280,
    height: 960,
    alt: 'Photo photo-12.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-13.jpeg',
    src: '/photos/photo-13.jpeg',
    width: 960,
    height: 1280,
    alt: 'Photo photo-13.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-14.jpeg',
    src: '/photos/photo-14.jpeg',
    width: 960,
    height: 1280,
    alt: 'Photo photo-14.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-15.jpeg',
    src: '/photos/photo-15.jpeg',
    width: 720,
    height: 1280,
    alt: 'Photo photo-15.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-2.jpeg',
    src: '/photos/photo-2.jpeg',
    width: 1206,
    height: 883,
    alt: 'Photo photo-2.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-3.jpeg',
    src: '/photos/photo-3.jpeg',
    width: 982,
    height: 1280,
    alt: 'Photo photo-3.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-4.jpeg',
    src: '/photos/photo-4.jpeg',
    width: 960,
    height: 1280,
    alt: 'Photo photo-4.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-5.jpeg',
    src: '/photos/photo-5.jpeg',
    width: 960,
    height: 1280,
    alt: 'Photo photo-5.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-6.jpeg',
    src: '/photos/photo-6.jpeg',
    width: 720,
    height: 1280,
    alt: 'Photo photo-6.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-7.jpeg',
    src: '/photos/photo-7.jpeg',
    width: 720,
    height: 1280,
    alt: 'Photo photo-7.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-8.jpeg',
    src: '/photos/photo-8.jpeg',
    width: 720,
    height: 1280,
    alt: 'Photo photo-8.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
  {
    id: 'photo-9.jpeg',
    src: '/photos/photo-9.jpeg',
    width: 720,
    height: 1280,
    alt: 'Photo photo-9.jpeg',
    camera: 'Digital Camera',
    focalLength: null,
    aperture: null,
    shutter: null,
    iso: null
  },
];
